export interface Ticketdata{
    flightID : Number,
    flightName : String,
    arrival : String,
    departure : String,
    price : Number,
    arrivalTime : String,
    departureTime : String,
    durationTime:  String,
    email :  String,
    phno :  String,
    title:  String,
    fname: String,
    lname: String,
    noofpassengers: String,
    title1:  String,
    fname1: String,
    lname1: String,
    title2:  String,
    fname2: String,
    lname2: String,
    fareprice: Number,
    discountedamount: String,
    totalprice:  Number
}